added some italian translation - needs review
the-djmaze/snappymail pull request #1094
Opened 2023-04-17 15:29 UTC by cm-schl

This translation is not complete and needs also some review.
Maybe this could help @lota? 🙂

2023-04-17 15:38 UTC, lota commented
sure @cm-schl I take a look, anyway not seems bad ;-) do you use automatic translator or a real person?

2023-04-17 15:45 UTC, lota requested changes
22: Sposta messagg(i) nel spam
26: Ricordami
29: Salvare le modifiche?
182: Sempre, se possibile
236: Sei sicuro di voler chiudere?

2023-04-17 15:45 UTC, lota commented on snappymail/v/0.0.0/app/localization/it-IT/user.json
> +		"MSG_DEFAULT_ACTION": "Azione standard",
Azione di default

2023-04-17 15:48 UTC, cm-schl commented
Thanks 🙂!
A real person 😉 but it's hard to find the correct words if someone has already began to translate - otherwise we would end up in a mix that would seem not logical to the end user 🙂

2023-04-18 07:40 UTC, lota commented
22: you cannot use "messagg(i) " because in italian

singolar is: *messaggio*
plural is: *messaggi*

I suppose the canonical lemma should be *messaggio/i*

410: without *?* not a question
![2023-04-18_09-38](https://user-images.githubusercontent.com/956392/232706279-8feba2b1-059f-4516-a60f-10b144759f31.png)

for me the a concise lemma is:

*Controlla nuove mail ogni*

(but is not literal translation, but better...)

Alessandro

2023-04-18 07:45 UTC, cm-schl commented
Hi,
right, therefore I thought it would be correct to say `messaggi(o)` but you're right with `messaggio/i`. So I will use that instead of `messaggi(o)`.
For 410 your perfectly right, that's a lot more clearer 👍

2023-04-18 09:55 UTC, the-djmaze commented
> A real person wink but it's hard to find the correct words if someone has already began to translate - otherwise we would end up in a mix that would seem not logical to the end user

You can also check below link if that helps
https://snappymail.eu/translate.php?lang=it-IT

2023-04-18 11:06 UTC, merged

2023-04-18 13:03 UTC, cm-schl commented
> > A real person wink but it's hard to find the correct words if someone has already began to translate - otherwise we would end up in a mix that would seem not logical to the end user
> 
> You can also check below link if that helps https://snappymail.eu/translate.php?lang=it-IT

Oh man, is this a new tool? Very helpful, didn't knew that this exists 🤦‍♂️

2023-04-20 14:32 UTC, simonedalpont commented
Hi,
I added some italian translations using your tool

[snappymail-it-IT.zip](https://github.com/the-djmaze/snappymail/files/11287213/snappymail-it-IT.zip)

let me know if you have any doubts about my translations. :)